import Title from "./components/Title";

export const storeProducts = [
  {
    id: 1,
    title: "Armani",
    img: "abdul/armani.jpg",
    price: 1330,
    Company: "Armani",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Channel",
    img: "abdul/channel.jpg",
    price: 930,
    Company: "Channel",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Versace",
    img: "abdul/colgne12.jpg",
    price: 770,
    Company: "Versace",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Mercedes Benz ",
    img: "abdul/mercedsBenz.jpg",
    price: 3469,
    Company: "Mercedes Benz",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Another1 ",
    img: "abdul/o.31508.jpg",
    price: 564,
    Company: "Another1",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Polo ",
    img: "abdul/polo.jpg",
    price: 2367,
    Company: "Polo",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Gucci",
    img: "abdul/gucci.jpg",
    price: 3700,
    Company: "Gucci",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Creed",
    img: "abdul/creed.jpg",
    price: 5700,
    Company: "Creed",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Bvlgari",
    img: "abdul/bvlgari.jpg",
    price: 4900,
    Company: "Bvlgari",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Eternity",
    img: "abdul/eternity.jpg",
    price: 2400,
    Company: "Eternity",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Boss",
    img: "abdul/boss.jpg",
    price: 1280,
    Company: "Boss",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Versace",
    img: "abdul/versace.jpg",
    price: 6000,
    Company: "Versace",
    info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Armani",
  img: "abdul/armani.jpg",
  price: 2330,
  Company: "Armani",
  info: "blah fjry asuiro ieyfgrnnn juuethsdg  hhjjsj",
  inCart: false,
  count: 0,
  total: 0,
};
